### ISSUE TITLE
Unit Testing Framework

### ISSUE THREAD

**Issue by trisyoungs** [projectdissolve/dissolve#221]
Implement suitable unit testing (e.g. via gtest)

**Comment by trisyoungs** [comment]
@rprospero Your PR #480 closes this?

**Comment by DanNixon** [comment]
We probably should not close this just yet as we still need to cover a sensible amount of things with tests.

**Comment by trisyoungs** [comment]
Framework was implemented by #480.  A list of required unit tests is in #496.
