### ISSUE TITLE
Restructure CI

### ISSUE THREAD

**Issue by DanNixon** [projectdissolve/dissolve#229]
Currently the CI does not follow a logical pipeline approach and is a simple collection of jobs.

In order to add static analysis, etc. this should be rearranged into pipelines of several smaller jobs.

Looking at the existing configurations, this would result in something like:

- master (pipeline)
  - static_analysis (stage)
    - cmake-format (job)
    - clang-format (job)
  - build_and_test (stage)
    - linux (job)
    - mac (job)
    - windows (job)
- pull_request (pipeline)
  - static_analysis (stage)
    - cmake-format (job)
    - clang-format (job)
  - build_and_test (stage)
    - linux (job)
    - mac (job)
    - windows (job)
  - system_tests (stage)
    - serial (job)
    - parallel (job)

**Comment by trisyoungs** [comment]
Questions / issues for PR #262.

- [ ] System tests - need to set system test names as an array parameter to ci/pipelines/templates/system-tests.yml. GH Actions had a trivial matrix format for this, which does not seem to be the case in AP.
- [ ] There are two pipelines that generate deployable artifacts (continuous.yml and release.yml) - best practice for building / deploying web content (Hugo) between these two streams?
- [ ] Old script to update / create releases on GitHub are present in the new scripts, but commented out for now. Still seems sensible to store binaries as releases on GitHub, side-by-side with the code, and link to these from the Dissolve website (updating the relevant links during the pipeline builds). Thoughts?

**Comment by DanNixon** [comment]
> System tests - need to set system test names as an array parameter to ci/pipelines/templates/system-tests.yml. GH Actions had a trivial matrix format for this, which does not seem to be the case in AP.

There is the matrix strategy, here is an example of it's use in Scipp: https://github.com/scipp/scipp/blob/master/.azure-pipelines/master.yml#L16-L20

However I'd argue that your system tests should not be orchestrated by your CI (at least this is very unconventional), what if a developer wants to run these locally?

> There are two pipelines that generate deployable artifacts (continuous.yml and release.yml) - best practice for building / deploying web content (Hugo) between these two streams?

Not too sure without more information about what you expect them to do.

> Old script to update / create releases on GitHub are present in the new scripts, but commented out for now. Still seems sensible to store binaries as releases on GitHub, side-by-side with the code, and link to these from the Dissolve website (updating the relevant links during the pipeline builds). Thoughts?

For releases, yes since they can be assets on a GH release. For nightly builds you can just use the artefacts functionality of Azure Pipelines.

> Remove old GH Actions workflows (except issues.yml).

Yes.

**Comment by trisyoungs** [comment]
Sorry, didn't make those original comments terribly clear! 

In Actions the system tests were run in parallel by specifying a matrix strategy of the form:

```
matrix:
  test: [atomshake, broadening, ..., rdfmethod]
```

While I'm aware of the general matrix strategy in AP yaml, I couldn't find an equivalent way of doing the above - tried an array parameter but couldn't get it to accept the syntax. All that the system-test.yml template does is run the specific test that is passed to it using the imaginatively-named `go` script in the `tests/` directory. If no test name is specified then that script runs all the tests in the `tests/` directory sequentially. Parallellising the tests seemed the logical thing to do. Testing locally simply amounts to running the script.

My query regarding the deployment of the website was really about how to effectively avoid clashes between deployments from the continuous build and release pipelines. Thinking about it, it seems best to restrict deployment of the website to the continuous build, keeping the documentation as up-to-date as possible, and not patching the docs on any hotfixes to the release (master) branch.

**Comment by DanNixon** [comment]
> While I'm aware of the general matrix strategy in AP yaml, I couldn't find an equivalent way of doing the above - tried an array parameter but couldn't get it to accept the syntax. All that the system-test.yml template does is run the specific test that is passed to it using the imaginatively-named `go` script in the `tests/` directory. If no test name is specified then that script runs all the tests in the `tests/` directory sequentially. Parallellising the tests seemed the logical thing to do. Testing locally simply amounts to running the script.

I think this is not a concern if my comments regarding test orchestration are addressed. As I mention, this should not be part of the CI.
Long term this should be moved to something like `ctest`, for now you could just create a shell script to run each test.

> Thinking about it, it seems best to restrict deployment of the website to the continuous build, keeping the documentation as up-to-date as possible, and not patching the docs on any hotfixes to the release (master) branch.

Yes, that seems sensible.

This is a tangent but in that case is the `master` branch only used for releases? If so it may be worth considering if this workflow is the best for the project as a simple feature branch workflow may be more appropriate (if you don't take advantage of the `master`/`develop` separation it is just an overhead that can be removed).
