### ISSUE TITLE
Charges in Lennard-Jones Potential not working

### ISSUE THREAD

**Issue by Alfam22** [projectdissolve/dissolve#237]
The atomic charges, specified in the atom type Lennard-Jones potential, are not being used in the calculation of the pair potentials.
i.e. Setting any charges for the atoms doesn't influence the pair potentials displayed in the plot.
So there is no Coulomb contribution to the potentials.

This is new in Dissolve -0.5.6. and was still working in 0.5.4.

**Operating System:**
Win7 64bit

Dissolve-GUI-0.5.6-d3569ec3-Win64

**Comment by trisyoungs** [comment]
The default choice of whether to include Coulomb terms in the pair potential changed in 0.5.6. Previous versions defaulted to generating pair potentials using atomic charges and short-range parameters specified on individual atom types.  Current versions assume the (more common) case where charges are given on the species' atoms instead, with just short-range parameters taken from the atom types.

Both behaviours can be selected by choosing the relevant option on the Forcefield tab, Pair Potentials section.
