### ISSUE TITLE
Crash when adding forcefield terms

### ISSUE THREAD

**Issue by calum-green** [projectdissolve/dissolve#354]
Can create a new species fine via the draw feature, but when assigning the forcefield terms (eg. OPSLAA2005/Aromatics for Benzene/ SPC/fw for water ) I am met with the message 'one or more AtomTypes in the imported species conflict with existing types' - when I 'finish' adding the forcefield terms and exit the pop-up, the programme completely crashes.

This occurs on the development build (updated 18th August) on windows 10. I repeated on 0.6.1 and the bug did not occur and I got the expected message of 'There are no naming conflicts with the imported AtomTypes'.

<img width="584" alt="FFBug24-08-20" src="https://user-images.githubusercontent.com/70141032/91044885-eb029600-e60d-11ea-9cdf-a1b3da42c840.png">

**Comment by trisyoungs** [comment]
I think this is an old bug fixed by #350 - it doesn't occur in the latest continuous build, as far as I can see.  Will close for now, but feel free to reopen if the problem persists.
