### ISSUE TITLE
'TorsionFunction keyword 'Cos3' requires 3 arguments, but 4 were provided'

### ISSUE THREAD

**Issue by calum-green** [projectdissolve/dissolve#360]
**Describe the bug**
Cannot run an input file on linux command line version that runs perfectly fine on windows-GUI - I am met with the error message: ''TorsionFunction' keyword 'Cos3' requires exactly 3 arguments, but 4 were provided. A screenshot of the output file is provided.

**To Reproduce**
Steps to reproduce the behaviour (if necessary):
1. Try and execute input file generated in windows-GUI version in linux command line
2. ran: dissolve filename.txt -n 50 > filename_out.txt

**Expected behaviour**
Should run perfectly fine as it does on the windows version

**Screenshots**
![LinuxError](https://user-images.githubusercontent.com/70141032/91560648-13ea9a00-e932-11ea-940a-747adafa1694.png)

**Operating System:**
 - OS:  Linux (on remote desktop machine)

**Comment by calum-green** [comment]
![LinuxError2](https://user-images.githubusercontent.com/70141032/91562474-2b775200-e935-11ea-9dd6-44ed46581e72.png)
There are 4 arguments to the Cos3 part of the master terms in the input file generated from the windows-GUI - if I delete the highlighted value on each Cos3 row the input file runs fine

**Comment by trisyoungs** [comment]
In actual fact the GUI version should also refuse to load that input file. This will be fixed shortly, but in the meantime you can manually edit the input file and delete the extra 0.000 from the Torsion lines to get things working.
