### ISSUE TITLE
Use SPDX license identifiers in file headers

### ISSUE THREAD

**Issue by DanNixon** [projectdissolve/dissolve#386]
See: https://spdx.dev/ids/

Using this format the header included in source files can be reduced to (or at least something like):
```
// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2020 Project Dissolve and contributors
```

You could use either [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html).

**Comment by DanNixon** [comment]
@trisyoungs If you decide on the exact wording I can make the change and add some tooling to keep the copyright year up to date.

**Comment by trisyoungs** [comment]
Great. If we can go for this, I'm happy to proceed.

```
// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2020 Team Dissolve and contributors
```
