### ISSUE TITLE
Crash on program launch -  Dissolve-GUI-0.7.0-f82267d-Win64

### ISSUE THREAD

**Issue by Alfam22** [projectdissolve/dissolve#427]
Installed the current continuous build 0.7.0-f82267d on Win7-64bit.
Program crashes with "does not respond" message.

When launching directly /bin/Dissolve.exe
the following error appears-see screenshot below.

The previous build 0.6.1 works and is stable.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/35522548/98360384-98882180-2021-11eb-98d2-d99b23575f62.png)

**Operating System:**
 - OS:  Windows 7 64 bit

**Comment by trisyoungs** [comment]
This is related to a recently-discovered issue specific to the Windows build. Version 0.7.0-d866740b (just built and available from the [continuous releases](https://github.com/projectdissolve/dissolve/releases/tag/continuous)) fixes the issue as far as we are aware. Please try this and let us know how you get on!

**Comment by trisyoungs** [comment]
Closing due to assumed resolution. Please reopen if this is not the case!
