### ISSUE TITLE
Impropers are missing in the force fild section of species

### ISSUE THREAD

**Issue by johannabusch** [projectdissolve/dissolve#435]
The Display of Impropers is missing in the force field section

![image](https://user-images.githubusercontent.com/56266543/98548906-633a3880-229a-11eb-85f9-8810574b0111.png)

**Comment by trisyoungs** [comment]
It is possible to load in one of the test inputs (`tests/energyforce4/py5-ntf2.txt`, for instance) and see a list of impropers displayed correctly. This is in fact an issue related to the copying of improper terms when running the Add Forcefield Terms wizard, and is addressed in #444.
