### ISSUE TITLE
Coordinate output file

### ISSUE THREAD

**Issue by HLaurent884** [projectdissolve/dissolve#457]
Hi Tris,

We were wondering if it would be possible for dissolve to output a text file after each iteration that contains all the atomic coordinates of all the molecules present in the same way the .ato file in EPSR works? It would allow us to extend analysis without you having to do loads of extra coding if we just wanted to try something quickly, and we are starting to make movies showing iteration steps and having such a file would make this much easier!

All the best,

Harry

**Comment by trisyoungs** [comment]
It certainly is - see https://forum.projectdissolve.com/t/saving-configurations-for-analysis-with-other-codes/.
