### ISSUE TITLE
restart file cannot be openend

### ISSUE THREAD

**Issue by johannabusch** [projectdissolve/dissolve#473]
when loading a simulation with a restart file, the following error message occurs and the GUI cannot be opened:
![image](https://user-images.githubusercontent.com/56266543/101639837-1334ca00-3a30-11eb-88f4-b6fa79c76708.png)

**Comment by trisyoungs** [comment]
From the reference input file you provided, this seems to be down to the EPSR widget in the GUI causing a segfault if there are no `Target`s defined in the module.
